llm_params:
  temperature: 0.7

mlflow_tracking_uri: "http://198.215.61.34:8153/"

# Concurrent requests
MAX_WORKERS: 5

# Application behavior constants
MAX_TURNS: 12
MAX_RETRIES: 3
RETRY_DELAY: 5 # Seconds