llm_params:
  temperature: 0.7

mlflow_tracking_uri: "http://localhost:5000"

# Concurrent requests
MAX_WORKERS: 10

# Application behavior constants
MAX_TURNS: 12
MAX_RETRIES: 3
RETRY_DELAY: 5 # Seconds